/**
 * *************************************************
 * Copyright (c) 2019, Grindrod Bank Limited
 * License MIT: https://opensource.org/licenses/MIT
 * **************************************************
 */
/*
 * A3S
 *
 * API Definition for the A3S. This service allows authentication, authorisation and accounting.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using za.co.grindrodbank.a3s.Converters;

namespace za.co.grindrodbank.a3s.A3SApiResources
{ 
        /// <summary>
        /// Enumeration to describe with what policy type you're busy with 
        /// </summary>
        /// <value>Enumeration to describe with what policy type you're busy with </value>
        [TypeConverter(typeof(CustomEnumConverter<PolicyType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PolicyType
        {
            
            /// <summary>
            /// Enum IPEnum for IP
            /// </summary>
            [EnumMember(Value = "IP")]
            IPEnum = 1,
            
            /// <summary>
            /// Enum CRONEnum for CRON
            /// </summary>
            [EnumMember(Value = "CRON")]
            CRONEnum = 2,
            
            /// <summary>
            /// Enum DATAEnum for DATA
            /// </summary>
            [EnumMember(Value = "DATA")]
            DATAEnum = 3
        }
}
